### ISSUE TITLE
Some Enhancements.

### ISSUE THREAD

**Issue by Guda-nemo** [katboi01/UmaViewer#15]
Hi there, I found a bug of uma's cutie sleeves, you can see in the picture.
![UmaViewer_2022-11-24_10-16-15-585](https://user-images.githubusercontent.com/82386665/203679520-1bea6777-8e97-4e98-85c1-9cf007c6e821.png)

I also noticed that we've got the function of recording cmd which is great!! Is this possible to have a funcion of extracting a pmf model?

**Comment by katboi01** [comment]
I don't see what the issue is right away, but I will check it, thanks for letting me know 👍 
Saving models at runtime is very niche, so it could take a long time for us to add it. And if it were added, then the models would most likely be exported to .fbx. So if you want to port the models to MMD, you shouldn't wait for the tool to be updated, at this time I'd say it's unlikely to be added.
