### ISSUE TITLE
I'm sorry, but I have some problem

### ISSUE THREAD

**Issue by diziyang** [katboi01/UmaViewer#18]
Are there any plans to add custom run paths later?
The memory footprint of umamusume was too large for my C drive, so I moved it to D drive and mapped it to the original path.
Although I can run the game normally in the dmm version, but this helper does not seem to work

**Comment by katboi01** [comment]
That's odd, I also have the directory remapped from C:// to N://, using Windows' symbolic link (junction mode if I recall correctly), and it works correctly.
Issues with file paths are hard to debug, because there are many things that can affect it, like system locale. Recently, there was a problem with files not loading when there are JP characters in the file path, that I couldn't find a fix for...
Tomorrow I will try to add a configuration file where you can set the path 👍

**Comment by diziyang** [comment]
Thank you very much for your reply and help

**Comment by katboi01** [comment]
Try this: https://github.com/katboi01/UmaViewer/releases/tag/2.1.5
When you first run it, a Config.json file will be created in the viewer's directory. You can change the location there (using text editor). Let me know if it works.

**Comment by diziyang** [comment]
Thank you very much for your help, it is now working, but I have found a new problem, the new version of umamusume haven't the master folder. However, I got the file from my friend that he downloaded two months ago, and it still work , So I would like to make a suggestion, maybe you can load this file in this program?

**Comment by katboi01** [comment]
This can't be right, I deleted my umamusume folder, started the game again, and the master folder was created automatically... I will wait for the download to finish and see what happens then. I haven't started the game in a long time.
